//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleto
    {
        public int ID_Boleto { get; set; }
        public Nullable<int> ID_Reserva { get; set; }
        public Nullable<int> ID_Asiento { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
