//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionAsiento
    {
        public int ID_Funcion { get; set; }
        public int ID_Asiento { get; set; }
        public Nullable<int> ID_EstadoAsiento { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual EstadoAsiento EstadoAsiento { get; set; }
        public virtual EstadoAsiento EstadoAsiento1 { get; set; }
        public virtual Funcion Funcion { get; set; }
        public virtual Funcion Funcion1 { get; set; }
    }
}
