//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int ID_Pago { get; set; }
        public Nullable<int> ID_Reserva { get; set; }
        public Nullable<int> ID_Metodo { get; set; }
        public Nullable<int> ID_Estadopago { get; set; }
        public System.DateTime PAG_Fecha { get; set; }
    
        public virtual EstadoPago EstadoPago { get; set; }
        public virtual EstadoPago EstadoPago1 { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual MetodoPago MetodoPago1 { get; set; }
        public virtual Reserva Reserva { get; set; }
        public virtual Reserva Reserva1 { get; set; }
    }
}
