//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pelicula()
        {
            this.Funcion = new HashSet<Funcion>();
            this.Funcion1 = new HashSet<Funcion>();
        }
    
        public int ID_Pelicula { get; set; }
        public Nullable<int> ID_Genero { get; set; }
        public string PEL_Titulo { get; set; }
        public System.TimeSpan PEL_Duracion { get; set; }
        public string PEL_Sinopsis { get; set; }
        public string PEL_ImagenURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcion> Funcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcion> Funcion1 { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Genero Genero1 { get; set; }
    }
}
